ALTER TABLE "BusinessSettings" ADD COLUMN "applyIgv" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Sale" ADD COLUMN "applyIgv" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Sale" ADD COLUMN "igvRate" DECIMAL(5,4) NOT NULL DEFAULT 0.18;
